added switcher
js-tasks-ru/htmlcss-20210708_warma2d pull request #15
Opened 2021-07-27 12:11 UTC by warma2d

2021-07-27 12:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-27 14:52 UTC, GSemikozov requested changes

2021-07-27 14:52 UTC, GSemikozov commented on 07-lection5/03-toggler/switcher.css
> +    transform: translate(-1%, -50%);
для .switcher__icon отступ слева (то, что позволяет двигать кружок при изменении состояния) лучше задавать в пикселях

2021-07-28 13:54 UTC, warma2d commented on 07-lection5/03-toggler/switcher.css
> +    transform: translate(-1%, -50%);
задал в px

2021-07-28 22:53 UTC, GSemikozov approved these changes

2021-07-28 22:54 UTC, merged