03 button dz
js-tasks-ru/htmlcss-20210708_warma2d pull request #3
Opened 2021-07-13 08:56 UTC by warma2d

2021-07-13 08:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-13 10:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-13 12:40 UTC, GSemikozov requested changes

2021-07-13 12:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше вместо такого курсора - pointer-events: none чтобы пользователь не мог нажать на disabled кнопку

2021-07-13 12:40 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
ширину лучше не фиксировать, пусть ширина определяется внутренним содержимым, а чтобы текст не прилипал к границам - можно задать паддинги. Если потребуется растянуть кнопку по ширине родителя - можно добавить класс-модификатор, например `.button_full_width. { width: 100%; }`

2021-07-14 07:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-14 22:59 UTC, warma2d commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Добавил `pointer-events: none;`

2021-07-14 23:00 UTC, warma2d commented on 03-lection1/01-button/button.css
> +    width: 182px;
width убрал

2021-07-15 13:36 UTC, GSemikozov approved these changes

2021-07-15 13:36 UTC, merged